version: '3'

services:
  db:
    container_name: nest-postgres-sequelize-sample
    image: postgres:14.5
    restart: always
    env_file:
      - ./.env
    ports:
      - 5433:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data